import Head from "next/head";

import { HomePage } from "@/containers/home/home.page";


// Import Swiper styles
// import 'swiper/css';
// import 'swiper/css/effect-coverflow';
// import 'swiper/css/pagination';

export default function Home() {
  return (
    <>
      <Head>
        <title>Dr Vikas Jindal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}
